using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AutoProperty.Generator;

[Generator]
public class AutoPropertyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Create a simple filter to find classes that might implement interfaces
        // change the return type to var for simplicity. 
        var pipeline = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: NodeIsEligibleForGeneration,
                transform: TransformNode)
            .Where(static x => x.HasValue) // filter out null
            .Select(static (x, _) =>
                x!.Value); // force result to the nullable value so GenerateOutput doesn't receive null parameters

        context.RegisterSourceOutput(pipeline, GenerateOutput);
    }


    private static bool NodeIsEligibleForGeneration(SyntaxNode node, CancellationToken cancellationToken = default)
        => node is ClassDeclarationSyntax { BaseList.Types.Count: > 0 };

    private static (string NamespaceName, string ClassName, string[] PropertyNames)? TransformNode(
        GeneratorSyntaxContext generatorContext,
        CancellationToken cancellationToken)
    {
        var classDeclaration = (ClassDeclarationSyntax)generatorContext.Node;

        var symbol = generatorContext.SemanticModel.GetDeclaredSymbol(classDeclaration, cancellationToken);
        // Classes (and interfaces) are represented as an INamedTypeSymbol in the model
        // INamedTypeSymbol is conceptually similar to System.Type
        if (symbol is not INamedTypeSymbol classSymbol)
        {
            // this shouldn't happen, given we're filtering to ClassDeclarations. But having it puts a safe guard in place so the generator does fail/crash.
            return null;
        }

        var classProperties = classSymbol
            .GetMembers()
            .OfType<IPropertySymbol>()
            .ToList();

// Get all the interfaces implemented by the class, and all properties from each interface.
        var interfaceProperties = classSymbol.AllInterfaces
            .SelectMany(i => i.GetMembers().OfType<IPropertySymbol>())
            .ToList();

// Compare and filter out any properties that are already implemented by the class 
        var unimplementedProperties = interfaceProperties
            .Where(i => !classProperties.Exists(c => c.Name == i.Name))
            .Select(i =>
            {
                var getAccessor = i.GetMethod != null ? "get;" : "";
                var setAccessor = i.SetMethod != null ? "set;" : "";

                setAccessor = i.SetMethod?.IsInitOnly ?? false ? "init;" : setAccessor;

                return $"public {i.Type} {i.Name} {{ {getAccessor} {setAccessor} }}";
            })
            .ToArray();

        return (
            classSymbol.ContainingNamespace.ToDisplayString(),
            classSymbol.Name,
            unimplementedProperties
        );
    }

    // type of second parameter is the type of the output of the transform function
    private static void GenerateOutput(SourceProductionContext context,
        (string NamespaceName, string ClassName, string[] PropertyNames) classToGenerate)
    {
        var properties = string.Join("\n\n\t\t\t", classToGenerate.PropertyNames);

        var sourceText = $$"""
                           /// <auto-generated>
                           namespace {{classToGenerate.NamespaceName}}
                           {
                               partial class {{classToGenerate.ClassName}}
                               {
                                   {{properties}}
                               }
                           }
                           """;

        context.AddSource($"{classToGenerate.NamespaceName}.{classToGenerate.ClassName}.g.cs", sourceText);
    }
}