using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AutoProperty.Generator;

internal record ClassToGenerate
{
    public string NamespaceName { get; set; }
    
    public string ClassName { get; set; }
    
    public EquatableArray<PropertyToGenerate> Properties { get; set; }
}


internal record PropertyToGenerate
{
    public string Visibility { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public bool HasGet { get; set; }

    public bool HasSet { get; set; }

    public bool IsInit { get; set; }
}


[Generator]
public class AutoPropertyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Create a simple filter to find classes that might implement interfaces
        // change the return type to var for simplicity. 
        var pipeline = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: NodeIsEligibleForGeneration,
                transform: TransformNode)
            .Where(static x => x != null);

        context.RegisterSourceOutput(pipeline, GenerateOutput);
    }


    private static bool NodeIsEligibleForGeneration(SyntaxNode node, CancellationToken cancellationToken = default)
        => node is ClassDeclarationSyntax { BaseList.Types.Count: > 0 };

    private static ClassToGenerate TransformNode(
        GeneratorSyntaxContext generatorContext,
        CancellationToken cancellationToken)
    {
        var classDeclaration = (ClassDeclarationSyntax)generatorContext.Node;

        var symbol = generatorContext.SemanticModel.GetDeclaredSymbol(classDeclaration, cancellationToken);
        // Classes (and interfaces) are represented as an INamedTypeSymbol in the model
        // INamedTypeSymbol is conceptually similar to System.Type
        if (symbol is not INamedTypeSymbol classSymbol)
        {
            // this shouldn't happen, given we're filtering to ClassDeclarations. But having it puts a safe guard in place so the generator does fail/crash.
            return null;
        }

        var classProperties = classSymbol
            .GetMembers()
            .OfType<IPropertySymbol>()
            .ToList();

// Get all the interfaces implemented by the class, and all properties from each interface.
        var interfaceProperties = classSymbol.AllInterfaces
            .SelectMany(i => i.GetMembers().OfType<IPropertySymbol>())
            .ToList();

// Compare and filter out any properties that are already implemented by the class 
        var unimplementedProperties = interfaceProperties
            .Where(i => !classProperties.Exists(c => c.Name == i.Name))
            .Select(i => new PropertyToGenerate()
            {
                Visibility = "public",
                Type = i.Type.ToDisplayString(),
                Name = i.Name,
                HasGet = i.GetMethod != null,
                HasSet = i.SetMethod != null,
                IsInit = i.SetMethod is {IsInitOnly: true},
            })
            .ToArray();

        return new ClassToGenerate()
        {
            NamespaceName = classSymbol.ContainingNamespace.ToDisplayString(),
            ClassName = classSymbol.Name,
            Properties = new EquatableArray<PropertyToGenerate>(unimplementedProperties)
        };
    }

    // type of second parameter is the type of the output of the transform function
    private static void GenerateOutput(SourceProductionContext context, ClassToGenerate classToGenerate)
    {
        var formattedProperties = classToGenerate.Properties.Select(i =>
        {
            var getAccessor = i.HasGet ? "get;" : "";
            var setAccessor = i.HasSet ? "set;" : "";

            setAccessor = i.IsInit ? "init;" : setAccessor;

            return $"{i.Visibility} {i.Type} {i.Name} {{ {getAccessor} {setAccessor} }}";
        });

        var properties = string.Join("\n\n\t\t\t", formattedProperties);

        var sourceText = $$"""
                           /// <auto-generated>
                           namespace {{classToGenerate.NamespaceName}}
                           {
                               partial class {{classToGenerate.ClassName}}
                               {
                                   {{properties}}
                               }
                           }
                           """;

        context.AddSource($"{classToGenerate.NamespaceName}.{classToGenerate.ClassName}.g.cs", sourceText);
    }
}